IzınTakip/Controllers/EmployeeDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using IzinTakip.Business.Abstract;
using IzinTakip.Entities.Concrete;
using IzinTakip.UI.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IzinTakip.UI.Controllers
{
    [Authorize]
    public class EmployeeDetailsController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IEmployeeAnnualDetailsService _employeeAnnualDetailsService;
        public WorkingDays calworkingDays = new WorkingDays();

        public EmployeeDetailsController(IEmployeeAnnualDetailsService employeeAnnualDetailsService, IEmployeeService employeeService)
        {
            _employeeAnnualDetailsService = employeeAnnualDetailsService;
            _employeeService = employeeService;
        }
        public async Task<IActionResult> Index(int empId)
        {
            var empAnnualDetails = await _employeeAnnualDetailsService.GetAllEmployeeAnnualDetailsByIdAsync(empId);
            var getEmpName = await _employeeService.FindEmployeeByIdAsync(empId);

            if (empAnnualDetails.Count != 0)
            {
                foreach (var item in empAnnualDetails)
                {
                    if (item.StartDate <= DateTime.Now && item.EndDate >= DateTime.Now)
                    {
                        item.IsOnLeave = true;
                    }
                    else { item.IsOnLeave = false; }

                    await _employeeAnnualDetailsService.UpdateAsync(item);
                }
            }
            ViewData["WorkerName"] = "Worker Name: " + getEmpName.Name;
            return View(empAnnualDetails.OrderBy(x => x.StartDate.Year).ToList());
        }

        [HttpGet]
        public IActionResult AddLeave(int empId)
        {
            ViewBag.empId = empId;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddLeave(int Id, EmployeeAnnualDetails employeeAnnualRights, int empId)
        {
            if (Id != employeeAnnualRights.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var employeeDetails = await _employeeService.FindEmployeeByIdAsync(empId);
                var allDataByEmp = await _employeeAnnualDetailsService.GetAllEmployeeAnnualDetailsByIdAsync(empId);
                int currentUsedDate = calworkingDays.HolidaysAsync(employeeAnnualRights.StartDate, employeeAnnualRights.EndDate);
                
                // Calculation Annual Rights based on the selected date.
                var recDate = employeeDetails.RecruitmentDate.Year;
                int currentDate = employeeAnnualRights.StartDate.Year;
                var value = currentDate - recDate;

                if (value < 1)
                {
                    employeeAnnualRights.AnnualRights = 0;
                }
                else if (value >= 1 && value <= 6)
                {
                    employeeAnnualRights.AnnualRights = 12;
                }
                else if (value > 6 && value <= 15)
                {
                    employeeAnnualRights.AnnualRights = 18;
                }
                else if (value > 15)
                {
                    employeeAnnualRights.AnnualRights = 24;
                }

                employeeAnnualRights.EmployeesId = empId;
                employeeAnnualRights.StartDate = employeeAnnualRights.StartDate;
                employeeAnnualRights.EndDate = employeeAnnualRights.EndDate.AddHours(23).AddMinutes(59);

                employeeAnnualRights.CreatedAt = DateTime.Now;
                employeeAnnualRights.UpdatedAt = DateTime.Now;

                employeeAnnualRights.LeftDate = employeeDetails.TotalAnnualRight - allDataByEmp.Sum(usedDate => usedDate.Used);

                if (calworkingDays.PublicHolidayDates.Count != 0)
                {
                    var createEmpDetWithPubHolidays = new AnnualLeaveViewModel()
                    {
                        CurrentUsedDate = currentUsedDate,
                        PublicHolidays = calworkingDays.PublicHolidayDates,
                        EmployeeAnnualDetails = employeeAnnualRights,
                    };
                    return View("HasPublicHoliday", createEmpDetWithPubHolidays);
                }
                else
                {
                    employeeAnnualRights.LeftDate -= currentUsedDate;
                    employeeAnnualRights.Used = currentUsedDate;
                }

                await _employeeAnnualDetailsService.CreateAsync(employeeAnnualRights);
                return RedirectToAction(nameof(Index), new { empId = empId });
            }

            return View(employeeAnnualRights);
        }

        [HttpPost]
        public async Task<IActionResult> AddLeaveWithPublicHoliday(AnnualLeaveViewModel annualLeaveViewModel)
        {
            if (ModelState.IsValid)
            {
                int counter = 0;
                foreach (var item in annualLeaveViewModel.PublicHolidays)
                {
                    if (item.IsChecked == true)
                    {
                        counter++;
                    }
                }
                int totalUsedDate = annualLeaveViewModel.CurrentUsedDate - counter;

                annualLeaveViewModel.EmployeeAnnualDetails.Used = totalUsedDate;
                annualLeaveViewModel.EmployeeAnnualDetails.LeftDate -= totalUsedDate;
            }

            await _employeeAnnualDetailsService.CreateAsync(annualLeaveViewModel.EmployeeAnnualDetails);
            return RedirectToAction(nameof(Index), new { empId = annualLeaveViewModel.EmployeeAnnualDetails.EmployeesId });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateWithPublicHoliday(AnnualLeaveViewModel annualLeaveViewModel)
        {
            if (ModelState.IsValid)
            {
                int counter = 0;
                foreach (var item in annualLeaveViewModel.PublicHolidays)
                {
                    if (item.IsChecked == true)
                    {
                        counter++;
                    }
                }
                int totalUsedDate = annualLeaveViewModel.CurrentUsedDate - counter;
                annualLeaveViewModel.EmployeeAnnualDetails.LeftDate -= (totalUsedDate - annualLeaveViewModel.EmployeeAnnualDetails.Used);
                annualLeaveViewModel.EmployeeAnnualDetails.Used = totalUsedDate;

                await _employeeAnnualDetailsService.UpdateAsync(annualLeaveViewModel.EmployeeAnnualDetails);

                return RedirectToAction(nameof(Index), new { empId = annualLeaveViewModel.EmployeeAnnualDetails.EmployeesId });
            }
            return RedirectToAction(nameof(Edit), new { empId = annualLeaveViewModel.EmployeeAnnualDetails.EmployeesId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var employeeDetails = await _employeeAnnualDetailsService.FindEmployeeAnnualDetailsByIdAsync(id);
            if (employeeDetails == null)
            {
                return NotFound();
            }
            return View(employeeDetails);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, EmployeeAnnualDetails employeeDetails)
        {
            if (Id != employeeDetails.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var updateEmpYearlyRight = await _employeeService.FindEmployeeByIdAsync(employeeDetails.EmployeesId);
                    int currentUsedDate = calworkingDays.HolidaysAsync(employeeDetails.StartDate, employeeDetails.EndDate);
                    
                    employeeDetails.UpdatedAt = DateTime.Now;
                    employeeDetails.StartDate = employeeDetails.StartDate;
                    employeeDetails.EndDate = employeeDetails.EndDate.AddHours(23).AddMinutes(59);
                    employeeDetails.AnnualRights = updateEmpYearlyRight.YearlyAnnualRightCount;

                    // Calculation Annual Rights based on the selected date.
                    var recDate = updateEmpYearlyRight.RecruitmentDate.Year;
                    int currentDate = employeeDetails.StartDate.Year;
                    var value = currentDate - recDate;

                    if (value < 1)
                    {
                        employeeDetails.AnnualRights = 0;
                    }
                    else if (value >= 1 && value <= 6)
                    {
                        employeeDetails.AnnualRights = 12;
                    }
                    else if (value > 6 && value <= 15)
                    {
                        employeeDetails.AnnualRights = 18;
                    }
                    else if (value > 15)
                    {
                        employeeDetails.AnnualRights = 24;
                    }

                    if (calworkingDays.PublicHolidayDates.Count != 0)
                    {
                        var upEmpDetWithPubHolidays = new AnnualLeaveViewModel()
                        {
                            CurrentUsedDate = currentUsedDate,
                            PublicHolidays = calworkingDays.PublicHolidayDates,
                            EmployeeAnnualDetails = employeeDetails,
                        };
                        return View("UpdateHasPublicHoliday", upEmpDetWithPubHolidays);
                    }

IzınTakip/Views/EmployeeDetails/-HasPublicHoliday.cshtml
@model IzinTakip.UI.AnnualLeaveViewModel

@{
    ViewData["Title"] = "Has public holiday!";
}

<!-- Basic form -->
<div class="col-md-12">
    <div class="panel panel-default">
        <header class="panel-heading">Following dates conflict with Public Holidays?</header>
        <div class="panel-body">
            <form asp-action="AddLeaveWithPublicHoliday">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <hr />
                <div class="form-group">
                    <label asp-for="EmployeeAnnualDetails.StartDate" class="control-label"></label>
                    <input type="Date" asp-for="EmployeeAnnualDetails.StartDate" class="form-control" disabled />
                    <span asp-validation-for="EmployeeAnnualDetails.StartDate" class="text-danger"></span>

                    <label asp-for="EmployeeAnnualDetails.EndDate" class="control-label"></label>
                    <input type="Date" asp-for="EmployeeAnnualDetails.EndDate" class="form-control" disabled />
                    <span asp-validation-for="EmployeeAnnualDetails.EndDate" class="text-danger"></span>
                </div>
                <hr />
                <h4>Following public holidays will not be encounterd as annual leave !</h4>
                <div class="form-group">
                    @{
                        @for (int i = 0; i < Model.PublicHolidays.Count; i++)
                        {
                            <div class="form-check">
                                @Html.CheckBoxFor(x => Model.PublicHolidays[i].IsChecked)
                                <label class="form-check-label">@Model.PublicHolidays[i].summary - @Model.PublicHolidays[i].start.date</label>
                            </div>
                        }
                    }
                </div>
                <div class="form-group">
                    <input type="submit" value="AddLeave" class="btn btn-success" />
                    <a asp-controller="Employee" asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>
                <input asp-for="EmployeeAnnualDetails.EmployeesId" class="form-control" type="hidden" />
                <input asp-for="CurrentUsedDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.LeftDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.Used" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.AnnualRights" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.CreatedAt" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.UpdatedAt" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.StartDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.EndDate" class="form-control" type="hidden" />
            </form>
        </div>
    </div>
</div>

IzınTakip/Views/EmployeeDetails/-UpdateHasPublicHoliday.cshtml
@model IzinTakip.UI.AnnualLeaveViewModel

@{
    ViewData["Title"] = "Update Entry with public holiday!";
}

<!-- Basic form -->
<div class="col-md-12">
    <div class="panel panel-default">
        <header class="panel-heading">Following dates conflict with Public Holidays?</header>
        <div class="panel-body">
            <form asp-action="UpdateWithPublicHoliday">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <hr />
                <div class="form-group">
                    <label asp-for="EmployeeAnnualDetails.StartDate" class="control-label"></label>
                    <input type="Date" asp-for="EmployeeAnnualDetails.StartDate" class="form-control" disabled />
                    <span asp-validation-for="EmployeeAnnualDetails.StartDate" class="text-danger"></span>

                    <label asp-for="EmployeeAnnualDetails.EndDate" class="control-label"></label>
                    <input type="Date" asp-for="EmployeeAnnualDetails.EndDate" class="form-control" disabled />
                    <span asp-validation-for="EmployeeAnnualDetails.EndDate" class="text-danger"></span>
                </div>
                <hr />
                <h4>Following public holidays will not be encounterd as annual leave !</h4>
                <div class="form-group">
                    @{
                        @for (int i = 0; i < Model.PublicHolidays.Count; i++)
                        {
                            <div class="form-check">
                                @Html.CheckBoxFor(x => Model.PublicHolidays[i].IsChecked)
                                <label class="form-check-label">@Model.PublicHolidays[i].summary - @Model.PublicHolidays[i].start.date</label>
                            </div>
                        }
                    }
                </div>
                <div class="form-group">
                    <input type="submit" value="AddLeave" class="btn btn-success" />
                    <a asp-controller="Employee" asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>
                <input asp-for="EmployeeAnnualDetails.Id" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.EmployeesId" class="form-control" type="hidden" />
                <input asp-for="CurrentUsedDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.LeftDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.Used" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.AnnualRights" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.CreatedAt" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.UpdatedAt" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.StartDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.EndDate" class="form-control" type="hidden" />
            </form>
        </div>
    </div>
</div>

IzınTakip/Views/EmployeeDetails/AddLeave.cshtml
@model IzinTakip.Entities.Concrete.EmployeeAnnualDetails

@{
    ViewData["Title"] = "AddLeave";
}

<!-- Basic form -->
<div class="col-md-12">
    <div class="panel panel-default">
        <a class="panel-heading">Create Leave</a>
        <div class="panel-body">
            <form asp-action="AddLeave">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group" id="IsOnLive">
                    <label asp-for="StartDate" class="control-label"></label>
                    <input type="Date" asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>

                    <label asp-for="EndDate" class="control-label"></label>
                    <input type="Date" asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="AddLeave" class="btn btn-success" />
                    <a asp-controller="Employee" asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>
                <input name="empId" value="@ViewBag.empId" class="form-control" type="hidden" />
            </form>
        </div>
    </div>
</div>

IzınTakip/Views/EmployeeDetails/Delete.cshtml
@model IzinTakip.Entities.Concrete.EmployeeAnnualDetails
@{
    ViewData["Title"] = "Delete Employee Details";
}

<div class="col-md-12">
    <div class="panel panel-default">
        <header class="panel-heading">Are you sure you want to delete @Model.Employees.Name 's details?</header>
        <div class="panel-body">
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger">Delete</button>
                <a asp-controller="EmployeeDetails" asp-action="Index" asp-route-empId="@Model.EmployeesId" class="btn btn-default">Back to List</a>
            </form>
        </div>
    </div>
</div>

IzınTakip/Views/EmployeeDetails/Edit.cshtml
@model IzinTakip.Entities.Concrete.EmployeeAnnualDetails

@{
    ViewData["Title"] = "Update EmployeeDetails";
}

<!-- Basic form -->
<div class="col-md-12">
    <div class="panel panel-default">
        <header class="panel-heading">Update Employee</header>
        <div class="panel-body">
            <form role="form" asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="Id" class="form-control" type="hidden"/>
                <input asp-for="EmployeesId" class="form-control" type="hidden"/>
                <input asp-for="AnnualRights" class="form-control" type="hidden"/>
                <input asp-for="Used" class="form-control" type="hidden"/>
                <input asp-for="LeftDate" class="form-control" type="hidden"/>
                <input asp-for="IsOnLeave" class="form-control" type="hidden"/>
                <input asp-for="CreatedAt" class="form-control" type="hidden"/>
                
                <hr />
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label"></label>
                    <input type="Date" asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>

                    <label asp-for="EndDate" class="control-label"></label>
                    <input type="Date" asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-success" />
                    <a asp-controller="EmployeeDetails" asp-action="Index" asp-route-empId="@Model.EmployeesId" class="btn btn-primary">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function myFunction() {
        var checkBox = document.getElementById("myCheck");
        var IsOnLive = document.getElementById("IsOnLive");
        if (checkBox.checked == true) {
            IsOnLive.style.display = "block";
        } else {
            IsOnLive.style.display = "none";
        }
    }
</script>

IzınTakip/Views/EmployeeDetails/HasPublicHoliday.cshtml
@model IzinTakip.UI.AnnualLeaveViewModel

@{
    ViewData["Title"] = "Has public holiday!";
}

<!-- Basic form -->
<div class="col-md-12">
    <div class="panel panel-default">
        <header class="panel-heading">Following dates conflict with Public Holidays?</header>
        <div class="panel-body">
            <form asp-action="AddLeaveWithPublicHoliday">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <hr />
                <div class="form-group">
                    <label asp-for="EmployeeAnnualDetails.StartDate" class="control-label"></label>
                    <input type="Date" asp-for="EmployeeAnnualDetails.StartDate" class="form-control" disabled />
                    <span asp-validation-for="EmployeeAnnualDetails.StartDate" class="text-danger"></span>

                    <label asp-for="EmployeeAnnualDetails.EndDate" class="control-label"></label>
                    <input type="Date" asp-for="EmployeeAnnualDetails.EndDate" class="form-control" disabled />
                    <span asp-validation-for="EmployeeAnnualDetails.EndDate" class="text-danger"></span>
                </div>
                <hr />
                <h4>Following public holidays will not be encounterd as annual leave !</h4>
                <div class="form-group">
                    @{
                        @for (int i = 0; i < Model.PublicHolidays.Count; i++)
                        {
                            <div class="form-check">
                                @Html.CheckBoxFor(x => Model.PublicHolidays[i].IsChecked)
                                <label class="form-check-label">@Model.PublicHolidays[i].summary - @Model.PublicHolidays[i].start.date</label>
                            </div>
                        }
                    }
                </div>
                <div class="form-group">
                    <input type="submit" value="AddLeave" class="btn btn-success" />
                    <a asp-controller="Employee" asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>
                <input asp-for="EmployeeAnnualDetails.EmployeesId" class="form-control" type="hidden" />
                <input asp-for="CurrentUsedDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.LeftDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.Used" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.AnnualRights" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.CreatedAt" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.UpdatedAt" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.StartDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.EndDate" class="form-control" type="hidden" />
            </form>
        </div>
    </div>
</div>

IzınTakip/Views/EmployeeDetails/Index.cshtml
@model ICollection<IzinTakip.Entities.Concrete.EmployeeAnnualDetails>;

@{
    ViewData["Title"] = "Employee Annual Details";
    Layout = "_Layout";
}

<!-- Responsive table -->
<div class="col-md-12">

    <div class="panel panel-default">
        <div class="panel-body">
            <a asp-action="AddLeave" asp-route-empId="@Model.Select(empId=> empId.EmployeesId).FirstOrDefault()" style="text-decoration: none; font-size: 2.0em;">Create New</a>
            <table id="index-table" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th data-toggle="true">Start Date</th>
                        <th data-toggle="true">End Date</th>
                        <th data-hide="phone,tablet">Annual Right</th>
                        <th data-hide="phone,tablet">Used</th>
                        @*<th data-hide="phone,tablet">Available</th>*@
                        <th data-hide="phone,tablet">Status</th>
                        <th data-hide="phone">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.StartDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EndDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AnnualRights)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Used)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.LeftDate)
                            </td>*@
                            @{
                                if (item.IsOnLeave == true)
                                {
                                    if (item.StartDate <= DateTime.Now && item.EndDate >= DateTime.Now)
                                    {
                                        <td data-value="3"><span class="label label-danger">On Leave</span></td>
                                    }
                                }
                                else
                                {
                                    if (item.StartDate >= DateTime.Now)
                                    {
                                        <td data-value="4"><span class="label label-info">Reserved</span></td>
                                    }
                                    else if (item.EndDate <= DateTime.Now)
                                    {
                                        <td data-value="4"><span class="label label-success">Completed</span></td>
                                    }
                                }
                            }
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Edit</a>
                                    @*<a asp-action="Details" asp-route-id="@item.Id" class="btn btn-default">Details</a>*@
                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- /Responsive table -->

IzınTakip/Views/EmployeeDetails/UpdateHasPublicHoliday.cshtml
@model IzinTakip.UI.AnnualLeaveViewModel

@{
    ViewData["Title"] = "Update Entry with public holiday!";
}

<!-- Basic form -->
<div class="col-md-12">
    <div class="panel panel-default">
        <header class="panel-heading">Following dates conflict with Public Holidays?</header>
        <div class="panel-body">
            <form asp-action="UpdateWithPublicHoliday">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <hr />
                <div class="form-group">
                    <label asp-for="EmployeeAnnualDetails.StartDate" class="control-label"></label>
                    <input type="Date" asp-for="EmployeeAnnualDetails.StartDate" class="form-control" disabled />
                    <span asp-validation-for="EmployeeAnnualDetails.StartDate" class="text-danger"></span>

                    <label asp-for="EmployeeAnnualDetails.EndDate" class="control-label"></label>
                    <input type="Date" asp-for="EmployeeAnnualDetails.EndDate" class="form-control" disabled />
                    <span asp-validation-for="EmployeeAnnualDetails.EndDate" class="text-danger"></span>
                </div>
                <hr />
                <h4>Following public holidays will not be encounterd as annual leave !</h4>
                <div class="form-group">
                    @{
                        @for (int i = 0; i < Model.PublicHolidays.Count; i++)
                        {
                            <div class="form-check">
                                @Html.CheckBoxFor(x => Model.PublicHolidays[i].IsChecked)
                                <label class="form-check-label">@Model.PublicHolidays[i].summary - @Model.PublicHolidays[i].start.date</label>
                            </div>
                        }
                    }
                </div>
                <div class="form-group">
                    <input type="submit" value="AddLeave" class="btn btn-success" />
                    <a asp-controller="Employee" asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>
                <input asp-for="EmployeeAnnualDetails.Id" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.EmployeesId" class="form-control" type="hidden" />
                <input asp-for="CurrentUsedDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.LeftDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.Used" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.AnnualRights" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.CreatedAt" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.UpdatedAt" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.StartDate" class="form-control" type="hidden" />
                <input asp-for="EmployeeAnnualDetails.EndDate" class="form-control" type="hidden" />
            </form>
        </div>
    </div>
</div>